
import { JobOffer, Diploma, PositionType, ContractType, AgeGroup, ActivityPeriod } from './types';

export const COMMUNES = [
  'Botsorhel',
  'Carantec',
  'Garlan',
  'Guerlesquin',
  'Guimaëc',
  'Henvic',
  'Lanmeur',
  'Lannéanou',
  'Le Cloître-Saint-Thégonnec',
  'Locquénolé',
  'Locquirec',
  'Morlaix',
  'Pleyber-Christ',
  'Plouégat-Guérand',
  'Plouégat-Moysan',
  'Plouezoc\'h',
  'Plougasnou',
  'Plougonven',
  'Plouigneau',
  'Plounéour-Ménez',
  'Plourin-lès-Morlaix',
  'Saint-Jean-du-Doigt',
  'Saint-Martin-des-Champs',
  'Saint-Thégonnec Loc-Eguiner',
  'Sainte-Sève',
  'Taulé',
];

// FIX: Added missing 'structureId' and 'userId' properties to each job offer to conform to the JobOffer type.
export const INITIAL_JOB_OFFERS: JobOffer[] = [
  {
    id: '1',
    title: 'Animateur / Animatrice périscolaire',
    structure: 'Mairie de Plougasnou',
    structureId: 'structure-plougasnou-1',
    userId: 'user-plougasnou-1',
    positionType: PositionType.ANIMATEUR,
    diplomas: [Diploma.BAFA],
    contractType: ContractType.CDD,
    ageGroups: [AgeGroup.THREE_TO_SIX, AgeGroup.SIX_TO_TWELVE],
    activityPeriods: [ActivityPeriod.MERCREDI, ActivityPeriod.HIVER, ActivityPeriod.PRINTEMPS, ActivityPeriod.AUTOMNE, ActivityPeriod.NOEL],
    startDate: '2024-09-01',
    endDate: '2025-06-30',
    commune: 'Plougasnou',
    contact: 'rh@plougasnou.fr',
    description: 'Recherche animateur/animatrice pour l\'accueil périscolaire matin et soir. Contrat de 20h/semaine. Expérience souhaitée.',
    active: true,
  },
  {
    id: '2',
    title: 'Directeur / Directrice de centre de loisirs',
    structure: 'Centre de loisirs de Carantec',
    structureId: 'structure-carantec-2',
    userId: 'user-carantec-2',
    positionType: PositionType.DIRECTEUR,
    diplomas: [Diploma.BAFD],
    contractType: ContractType.CEE,
    ageGroups: [AgeGroup.SIX_TO_TWELVE, AgeGroup.TWELVE_TO_EIGHTEEN],
    activityPeriods: [ActivityPeriod.ETE],
    startDate: '2024-07-01',
    endDate: '2024-08-31',
    commune: 'Carantec',
    contact: 'contact@alsh-carantec.bzh',
    description: 'Nous cherchons un directeur ou une directrice pour nos accueils de loisirs d\'été. Prise de poste mi-juin pour préparation. Forte autonomie demandée.',
    active: true,
  },
  {
    id: '3',
    title: 'Animateur sportif',
    structure: 'Service Jeunesse Morlaix',
    structureId: 'structure-morlaix-3',
    userId: 'user-morlaix-3',
    positionType: PositionType.ANIMATEUR,
    diplomas: [Diploma.BPJEPS],
    contractType: ContractType.CEE,
    ageGroups: [AgeGroup.SIX_TO_TWELVE, AgeGroup.TWELVE_TO_EIGHTEEN],
    activityPeriods: [ActivityPeriod.AUTOMNE],
    startDate: '2024-10-21',
    endDate: '2024-11-03',
    commune: 'Morlaix',
    contact: 'jeunesse@villedemorlaix.org',
    description: 'Animateur/trice pour encadrer des stages multisports pour les 10-14 ans durant les vacances de la Toussaint.',
    active: true,
  },
  {
    id: '4',
    title: 'Animateur pour camp d\'été',
    structure: 'Accueil Jeunes de Saint-Martin',
    structureId: 'structure-stmartin-4',
    userId: 'user-stmartin-4',
    positionType: PositionType.ANIMATEUR,
    diplomas: [Diploma.BAFA, Diploma.STAGIAIRE],
    contractType: ContractType.CEE,
    ageGroups: [AgeGroup.TWELVE_TO_EIGHTEEN],
    activityPeriods: [ActivityPeriod.ETE],
    startDate: '2024-07-15',
    endDate: '2024-08-15',
    commune: 'Saint-Martin-des-Champs',
    contact: 'aj.stmartin@email.com',
    description: 'Animateur/trice avec spécialité "grands jeux" ou "nature" pour des camps sous tente. Permis B indispensable.',
    active: true,
  },
   {
    id: '5',
    title: 'Surveillant de baignade pour mini-camps',
    structure: 'Mairie de Locquirec',
    structureId: 'structure-locquirec-5',
    userId: 'user-locquirec-5',
    positionType: PositionType.SURVEILLANT,
    diplomas: [Diploma.SB, Diploma.BAFA],
    contractType: ContractType.CEE,
    ageGroups: [AgeGroup.SIX_TO_TWELVE],
    activityPeriods: [ActivityPeriod.ETE],
    startDate: '2024-07-08',
    endDate: '2024-07-26',
    commune: 'Locquirec',
    contact: 'enfance@locquirec.fr',
    description: 'Encadrement de mini-camps pour les 8-12 ans sur la côte. Thématique voile et activités nautiques. Surveillance des temps de baignade.',
    active: false,
  },
];